spring:
  datasource:
    url: jdbc:tc:mysql:8.0://localhost/some_db?TC_MY_CNF=sql/config&TC_INITSCRIPT=file:src/main/resources/sql/schema.sql
logging:
  level:
    org.springframework.jdbc.core: trace